export const fakeBranches = [
  {
    id: 1,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Yangon Main Campus',
    established_year: '2015',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image:
      'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    phone_number_1: '09-123456789',
    phone_number_2: '09-987654321',
    email_address: 'yangon@brightfuture.edu.mm',
    campus_address: 'No. 120, Pyay Road, Kamayut Township, Yangon',
    logo_image:
      'https://placehold.co/200x200/2563eb/ffffff?text=BFIS',
    is_main_branch: true,
  },
  {
    id: 2,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Mandalay Campus',
    established_year: '2018',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image:
      'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    phone_number_1: '09-234567891',
    phone_number_2: '09-876543219',
    email_address: 'mandalay@brightfuture.edu.mm',
    campus_address: 'No. 45, 62nd Street, Chanayethazan Township, Mandalay',
    logo_image:
      'https://placehold.co/200x200/2563eb/ffffff?text=BFIS',
    is_main_branch: false,
  },
  {
    id: 3,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Naypyidaw Campus',
    established_year: '2021',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image:
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    phone_number_1: '09-345678912',
    phone_number_2: '09-765432198',
    email_address: 'naypyidaw@brightfuture.edu.mm',
    campus_address: 'No. 88, Thapyaygone Quarter, Zabuthiri Township, Naypyidaw',
    logo_image:
      'https://placehold.co/200x200/2563eb/ffffff?text=BFIS',
    is_main_branch: false,
  },
  {
    id: 4,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Ayerawady Campus',
    established_year: '2026',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkqcoyYt-BFtJE_QLBf4a1OS_BFRsoRfQfsH3pGcD7Ng&s=10',
    phone_number_1: '09-345678912',
    phone_number_2: '09-765432198',
    email_address: 'ayawady@brightfuture.edu.mm',
    campus_address: 'No. 88, Thapyaygone Quarter, Zabuthiri Township, Naypyidaw',
    logo_image:
      'https://thumbs.dreamstime.com/b/modern-school-logo-featuring-stylized-book-icon-symbolizing-education-learning-sleek-design-graduation-cap-315282989.jpg',
    is_main_branch: false,
  },
  {
    id: 5,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Ayerawady Campus',
    established_year: '2026',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkqcoyYt-BFtJE_QLBf4a1OS_BFRsoRfQfsH3pGcD7Ng&s=10',
    phone_number_1: '09-345678912',
    phone_number_2: '09-765432198',
    email_address: 'ayawady@brightfuture.edu.mm',
    campus_address: 'No. 88, Thapyaygone Quarter, Zabuthiri Township, Naypyidaw',
    logo_image:
      'https://thumbs.dreamstime.com/b/modern-school-logo-featuring-stylized-book-icon-symbolizing-education-learning-sleek-design-graduation-cap-315282989.jpg',
    is_main_branch: false,
  },
  {
    id: 6,
    school_name: 'Bright Future International School',
    type_of_institution: 'Private School',
    branch: 'Ayerawady Campus',
    established_year: '2026',
    website_url: 'https://www.brightfuture.edu.mm',
    branch_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkqcoyYt-BFtJE_QLBf4a1OS_BFRsoRfQfsH3pGcD7Ng&s=10',
    phone_number_1: '09-345678912',
    phone_number_2: '09-765432198',
    email_address: 'ayawady@brightfuture.edu.mm',
    campus_address: 'No. 88, Thapyaygone Quarter, Zabuthiri Township, Naypyidaw',
    logo_image:
      'https://thumbs.dreamstime.com/b/modern-school-logo-featuring-stylized-book-icon-symbolizing-education-learning-sleek-design-graduation-cap-315282989.jpg',
    is_main_branch: false,
  },
]